[package]
name = "CLI-Miner"
version = "0.1.0"
edition = "2021"

[dependencies]
clang = "2.0.0"
clearscreen = "4.0.1"
crossterm = "0.28.1"
kira = "0.10.2"
ratatui = { version = "0.29.0", features = ["all-widgets"] }
target = "2.1.0"
windows_x86_64_gnu = "0.53.0"
