[target.aarch64-linux-android]
linker = "aarch64-linux-android29-clang"

[package]
name = "CLI-Miner"
version = "0.1.0"
edition = "2021"

[dependencies]
discord-rich-presence = "0.2.5"
ratatui = { version = "0.29.0", features = ["all-widgets"] }
rodio = "0.20.1"
windows_x86_64_gnu = "0.53.0"
